### ISSUE TITLE
关键字问题

### ISSUE THREAD

**Issue by SonderXiaoming** [Rlezzo/WifeGacha#1]
![image](https://github.com/user-attachments/assets/6e6b3041-f931-4f4f-aa63-8798a93e1aa8)
这触发有问题吧，怎么带关键字就离了，应该是判断纯粹吹水不反应。其他关键字好像有同样的问题。
救救

**Comment by Rlezzo** [comment]
关键词的问题处理了，如果不想管理帮别人抽老婆或者离婚的话，把on_prefix改成一个fullmatch也可以
