### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by SonderXiaoming** [Rlezzo/WifeGacha#2]
1. 
![image](https://github.com/user-attachments/assets/cc239a1c-d7e7-4118-b5bd-33d83a2842db)
能显示一下老婆头像最好，好看一点
2. 关于好感的建议，可以好感高的不容易被牛，比如我好感20，他好感10，他牛我要困难，我牛他容易。离婚可以降低好感。关于随机回复甜言蜜语，我有个低配版想法就是每个角色单独写几条（靠大家征集），如果没有的角色就给个默认的几条。
3. 牛老婆现在限制次数我觉得不如设置个半小时的cd，互动性高一点，被别人牛了也很快可以报仇。最好限制一下一个人一天最多可以被牛几次，现在容易被一群人针对牛。

**Comment by Rlezzo** [comment]
1.await bot.send(ev, f"{ug_wife.image_path}誰にでも優しくしないで, でもそこが好き！\n({ug_wife.name}好感度加一)")
你在main.py找到这句，加个{ug_wife.image_path}就行了，ug_wife.image_path就是图片CQ码。

3.限制次数和设置cd这个，我直接用的hoshino自带的类，你看基本参数那块，结合下面的用法研究一下就懂了，很好改的。

2.关于好感度这个，是因为群友觉得抽到了什么都干不了，很无聊，就加了个日老婆。目前没有精力再进一步想玩法了，好感高的不容易被牛这个想法之前和群友讨论过的，但是如果没有完整的一套玩法，加个一两点变化也会很快就感觉无聊，毕竟最开始这是个每天抽一个老婆图片的简单插件，就和运势一样。
如果你有好的玩法，可以fork一份自己改，我也就抛砖引玉做了个这玩意，后续拓展确实目前没时间做。
最后关于征集角色台词这个，工作量听着还挺大，AI做其实挺简单，如果有可以联网的AI API，然后把角色名都改成游戏-角色名的格式，每次让AI自己找对应角色的人设资料然后做出回复，可能比较简单而且有新鲜感。
如果征集了角色台词，可以用alembic修改数据库，给角色表关联个台词表什么的，也可以简单一点，直接用json，然后读角色名对应的台词
不过我确实没时间精力做了，可能需要你自己定制修改，有问题我可以尽量帮你

**Comment by SonderXiaoming** [comment]
感谢，只是讨论功能而已，做是会做的。（我也没时间）插件很有意思，潜力很大。
