### ISSUE TITLE
插件内存使用异常

### ISSUE THREAD

**Issue by LeoWrDeom** [Rlezzo/WifeGacha#5]
启用插件前
![4ed8750e30f6c261bcda82f9cf7aae40](https://github.com/user-attachments/assets/7c74618a-dd6b-41f7-8e2e-c85470c65803)
启用插件后
![252a54dc9a01dbe4d1c85b4fa12c34db](https://github.com/user-attachments/assets/c5de8953-78e3-4104-9945-fb4fbd9b02c5)
不知道这是不是正常现象，时间长了CPU使用率貌似也会升高

**Comment by 1011yoshino** [comment]
已修复，更新一下就好了。内存占用过高是因为图鉴完整地预加载了所有图片，已经更改成了预加载80*80的缩略图。且增加了开关，如果你不需要预加载图片可以将PRELOAD 更改为 False
